# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'WXLogin' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for WXLogin
pod 'WechatOpenSDK'
pod 'AFNetworking'
  target 'WXLoginTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'WXLoginUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
